#ifndef MENUHEADER_H_INCLUDED
#define MENUHEADER_H_INCLUDED

#define MENU_ID 101
#define EXIT_ID 9001
#define DDA 9002
#define MIDPOINT_LINE 9003
#define CARTESIAN_CIRCLE 9004


#endif // MENUHEADER_H_INCLUDED
